module.exports = {

  GET_MARKDOWN: 'GET_MARKDOWN',
  GET_MARKDOWN_SUCCESS: 'GET_MARKDOWN_SUCCESS',
  GET_MARKDOWN_FAIL: 'GET_MARKDOWN_FAIL',

  GET_CODE: 'GET_CODE',
  GET_CODE_SUCCESS: 'GET_CODE_SUCCESS',
  GET_CODE_FAIL: 'GET_CODE_FAIL',

  SET_CODE: 'SET_CODE'
};