module.exports = {

  GET_MARKDOWN: 'GET_MARKDOWN',
  GET_MARKDOWN_SUCCESS: 'GET_MARKDOWN_SUCCESS',
  GET_MARKDOWN_FAIL: 'GET_MARKDOWN_FAIL',

  GET_RUST: 'GET_RUST',
  GET_RUST_SUCCESS: 'GET_RUST_SUCCESS',
  GET_RUST_FAIL: 'GET_RUST_FAIL'

};